### ISSUE TITLE
Insults are not shown

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/c-sharp-desktop#8]
The program tells "The Server did not provide any data".

![error](https://user-images.githubusercontent.com/19539741/94999380-446cc600-05b9-11eb-9955-a280feea139e.PNG)

@Schokobecher, can you please have a look?

One Indian out there can fix the typo "Server" --> "server" please.

**Comment by Schokobecher** [comment]
Supported TLS versions of the server seem to have changed.

Should be fixed in #10 

A new release and update package needs to be built:see_no_evil: 
After that, I think it would be best to archive this repo as I don't work with C# anymore.

**Comment by EvilInsultGenerator** [comment]
I will leave the repo active but we can start a Python desktop client and redesign the website next year. 
Thank you so much for your help! 😘
